# canonical.py
canonical_items = [
    {"id": "Atr1",  "text": "When one of us apologizes when discussions go in a bad direction, the issue does not extend."},
    {"id": "Atr2",  "text": "I know we can ignore our differences, even if things get hard sometimes."},
    {"id": "Atr3",  "text": "When we need it, we can take our discussions from the beginning and correct it."},
    {"id": "Atr4",  "text": "When I argue with my wife, it will eventually work for me to contact her."},
    {"id": "Atr5",  "text": "The time I spent with my wife is special for us."},
    {"id": "Atr6",  "text": "We don't have time at home as partners."},
    {"id": "Atr7",  "text": "We are like two strangers who share the same environment at home rather than family."},
    {"id": "Atr8",  "text": "I enjoy our holidays with my wife."},
    {"id": "Atr9",  "text": "I enjoy traveling with my wife."},
    {"id": "Atr10", "text": "My wife and I have most of our goals in common."},
    {"id": "Atr11", "text": "In the future, when I look back, I see that my wife and I are in harmony with each other."},
    {"id": "Atr12", "text": "My wife and I have similar values in terms of personal freedom."},
    {"id": "Atr13", "text": "My wife and I have similar entertainment preferences."},
    {"id": "Atr14", "text": "Most of our goals for people (children, friends, etc.) are the same."},
    {"id": "Atr15", "text": "Our dreams of living together are similar and harmonious."},
    {"id": "Atr16", "text": "We're compatible about what love should be."},
    {"id": "Atr17", "text": "We share the same views about being happy in life."},
    {"id": "Atr18", "text": "We have similar ideas about how marriage should be."},
    {"id": "Atr19", "text": "We have similar ideas about how roles should be in marriage."},
    {"id": "Atr20", "text": "We have similar values in trust."},
    {"id": "Atr21", "text": "I know exactly what my wife likes."},
    {"id": "Atr22", "text": "I know how my wife wants to be taken care of when she's sick."},
    {"id": "Atr23", "text": "I know my wife's favorite food."},
    {"id": "Atr24", "text": "I can tell what kind of stress my wife is facing in her life."},
    {"id": "Atr25", "text": "I have knowledge of my wife's inner world."},
    {"id": "Atr26", "text": "I know my wife's basic concerns."},
    {"id": "Atr27", "text": "I know what my wife's current sources of stress are."},
    {"id": "Atr28", "text": "I know my wife's hopes and wishes."},
    {"id": "Atr29", "text": "I know my wife very well."},
    {"id": "Atr30", "text": "I know my wife's friends and their social relationships."},
    {"id": "Atr31", "text": "I feel aggressive when I argue with my wife."},
    {"id": "Atr32", "text": "When discussing with my wife, I usually use expressions such as 'you always' or 'you never'."},
    {"id": "Atr33", "text": "I can use negative statements about my wife's personality during discussions."},
    {"id": "Atr34", "text": "I can use offensive expressions during our discussions."},
    {"id": "Atr35", "text": "I can insult during discussions."},
    {"id": "Atr36", "text": "I can be humiliating when we argue."},
    {"id": "Atr37", "text": "My argument with my wife is not calm."},
    {"id": "Atr38", "text": "I hate my wife's way of bringing it up."},
    {"id": "Atr39", "text": "Fights often occur suddenly."},
    {"id": "Atr40", "text": "We start a fight before I know what's going on."},
    {"id": "Atr41", "text": "When I talk to my wife about something, my calm suddenly breaks."},
    {"id": "Atr42", "text": "When I argue with my wife, I just snap and don't say a word."},
    {"id": "Atr43", "text": "I'm mostly thirsty to calm the environment a little bit."},
    {"id": "Atr44", "text": "Sometimes I think it's good for me to leave home for a while."},
    {"id": "Atr45", "text": "I'd rather stay silent than argue with my wife."},
    {"id": "Atr46", "text": "Even if I'm right in the argument, I don't want to upset the other side."},
    {"id": "Atr47", "text": "When I argue with my wife, I remain silent because I fear losing control of my anger."},
    {"id": "Atr48", "text": "I feel right in our discussions."},
    {"id": "Atr49", "text": "I have nothing to do with what I've been accused of."},
    {"id": "Atr50", "text": "I'm not actually the one who's guilty about what I'm accused of."},
    {"id": "Atr51", "text": "I'm not the one who's wrong about problems at home."},
    {"id": "Atr52", "text": "I wouldn't hesitate to tell her about my wife's inadequacy."},
    {"id": "Atr53", "text": "When I discuss, I remind her of my wife's inadequate issues."},
    {"id": "Atr54", "text": "I'm not afraid to tell her about my wife's incompetence."}
]

FEATURES = [c["id"] for c in canonical_items]
ID2TEXT = {c["id"]: c["text"] for c in canonical_items}
